version: '3.7'

services:            
  web-api:
    image: web-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8888
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https/aspnetapp.pfx:/https/aspnetapp.pfx:ro